name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install package (editable) + test deps
        run: |
          uv pip install -e .
          uv pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest -q --cov=protoswift --cov-report=term-missing
